version: "3.9"
services:
  aws:
    build: ./AWS
    ports:
      - "3003:3003"
    command: node Server.js
  gpt:
    build: ./ChatGPT
    ports:
      - "3005:3005"
    command: node chatgpt.js
  geo:
    build: ./geo-service
    ports:
      - "3000:3000"
  receipt:
    build: ./Receipts
    ports:
      - "3004:54102"
    command: node index.js
  tesseract:
    build: ./Tesseract-ImageProcess
    ports:
      - "3002:3002"
    command: node server/index.js